# Makefile for Memory Allocator Project (C++17)

CXX      = g++
CXXFLAGS = -Wall -Wextra -O2 -g -std=c++17 -MMD -MP
LDFLAGS  =

# Source files
ALLOCATOR_SRC  = allocator.cpp memlib.cpp
CHECKPOINT_SRC = test_checkpoint.cpp
FINAL_SRC      = test_final.cpp

# Object files
ALLOCATOR_OBJ  = $(ALLOCATOR_SRC:.cpp=.o)
CHECKPOINT_OBJ = $(CHECKPOINT_SRC:.cpp=.o)
FINAL_OBJ      = $(FINAL_SRC:.cpp=.o)

# Dependency files (auto-generated by -MMD -MP)
# If you edit allocator.h or memlib.h, affected .cpp files recompile automatically
DEPS = $(ALLOCATOR_OBJ:.o=.d) $(CHECKPOINT_OBJ:.o=.d) $(FINAL_OBJ:.o=.d)

# Executables
CHECKPOINT_EXE = test_checkpoint
FINAL_EXE      = test_final

# ── Default target ────────────────────────────────────────────────────────────
all: $(FINAL_EXE)

# ── Link ─────────────────────────────────────────────────────────────────────
$(CHECKPOINT_EXE): $(ALLOCATOR_OBJ) $(CHECKPOINT_OBJ)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

$(FINAL_EXE): $(ALLOCATOR_OBJ) $(FINAL_OBJ)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

# ── Compile (with automatic header dependency tracking) ───────────────────────
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $<

# Pull in auto-generated dependency files (silently ignore if missing)
-include $(DEPS)

# ── Run targets ──────────────────────────────────────────────────────────────
test-checkpoint: $(CHECKPOINT_EXE)
	./$(CHECKPOINT_EXE)

test-final: $(FINAL_EXE)
	./$(FINAL_EXE)

test: test-checkpoint test-final

# ── AddressSanitizer build ────────────────────────────────────────────────────
# Catches memory errors (out-of-bounds writes, use-after-free, etc.)
# Run with: make asan && ./test_checkpoint   or   ./test_final
#
# Note: ASAN will report a leak in memlib.cpp because it uses the real
# malloc internally. Suppress with: ASAN_OPTIONS=detect_leaks=0 ./test_final
asan: CXXFLAGS += -fsanitize=address,undefined -fno-omit-frame-pointer -O1
asan: clean all

# ── Utility ──────────────────────────────────────────────────────────────────
clean:
	rm -f $(ALLOCATOR_OBJ) $(CHECKPOINT_OBJ) $(FINAL_OBJ)
	rm -f $(DEPS)
	rm -f $(CHECKPOINT_EXE) $(FINAL_EXE)
	rm -f *~ *.core

rebuild: clean all

.PHONY: all test test-checkpoint test-final asan clean rebuild
